"""Add agent details (first_name, last_name, nin_image)

Revision ID: d1234567890a
Revises: 76e20822d49f
Create Date: 2026-03-04 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1234567890a'
down_revision: Union[str, Sequence[str], None] = '76e20822d49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('nin_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'nin_image')
    op.drop_column('agents', 'last_name')
    op.drop_column('agents', 'first_name')
    # ### end Alembic commands ###
